kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: eap-app
  namespace: america
  labels:
    app: eap-app
    app.kubernetes.io/component: eap-app
    app.kubernetes.io/instance: eap-app
    app.kubernetes.io/name: eap-app
    app.kubernetes.io/part-of: eap-app
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.io/imported-from: 'docker.io/ricardoaraujo75/eap-app:latest'
      from:
        kind: DockerImage
        name: 'docker.io/ricardoaraujo75/eap-app:latest'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Local
